@extends('layouts.site')

@section('content')

<section class="slider-cont innerpage-heading">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 slider-tagline">
                <h1>TERMS OF SERVICE</h1>
            </div>
        </div>
    </div>
</section>
<div class="innerpage-cont">
    <section class="home-part1  price-plan-cont">
        <div class="container">
            <div class="row">                
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 products-txt1"> 
                    <p><strong>IMPORTANT, READ CAREFULLY: YOUR USE OF AND ACCESS TO THE WEBSITE AND PRODUCTS AND SERVICES AND ASSOCIATED SOFTWARE (COLLECTIVELY, THE "SERVICES") OF CLOUDLINE ("CLOUDLINE") IS CONDITIONED UPON YOUR COMPLIANCE AND ACCEPTANCE OF THESE TERMS.</strong></p> <br/>
                            <p><strong>BY CLICKING/CHECKING THE "I AGREE" BUTTON/BOX, ACCESSING THE CLOUDLINE WEBSITE OR BY UTILIZING THE CLOUDLINE SERVICES YOU AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS. THE CLOUDLINE SERVICES ARE NOT AVAILABLE TO PERSONS WHO ARE NOT LEGALLY ELIGIBLE TO BE BOUND BY THESE TERMS OF SERVICE.</strong> </p> <br /> <br />
                        This is a legal agreement ("Agreement") between you and Cloudline for use of the Services which you selected or initiated. "You" refers to the individual who is using or accessing the Services or is registered and/or has provided his or her credit card or other payment mechanism for the Services either directly with Cloudline or through a third party or, if an individual is purchasing the Services on behalf of an entity and is authorized to purchase the Services on behalf of such entity, then "You" refers to such entity. If you do not agree with the terms of this Agreement, do not use or access the Services or, when applicable, click the "Cancel" button and do not purchase the Services.<br />
                        Any software associated with the Services and website is protected by copyright laws and international copyright treaties, as well as other intellectual property laws and treaties. <br /> <br/>
                        <strong>1. SERVICES</strong> <br/> Cloudline will provide the Services in accordance with this Agreement. If you order Services through an on-line registration page or an order form (an "Order Form"), the Order Form may contain additional terms and conditions and information regarding the Services you are ordering. Unless otherwise expressly set forth in any such additional terms and conditions applicable to the specific Service which you choose to use, those additional terms are hereby incorporated into this Agreement in relation to your use of that Service. Cloudline may at its sole discretion, discontinue the Services or modify the features of the Services from time to time without prior notice. Use of the Services requires one or more compatible devices, Internet access (fees may apply), and certain software (fees may apply), and may require obtaining updates or upgrades from time to time. Because use of the Services involves hardware, software, and Internet access, your ability to use such Services may be affected by the performance of these factors. High speed Internet access is recommended. You acknowledge and agree that such system requirements, which may be changed from time to time, are your responsibility. The following defined terms may appear in your Order Form:
                        <li>"Host" means an individual who can schedule and start Meetings. </li>
                        <li>"Meeting" means a Cloudline meeting.</li>
                        <li>"Order Start Date" means the date an Initial Subscription Term begins as specified in an Order Form.</li>
                        <li>"Participant" means an individual, other than the Host, who participates in a Meeting.</li>
                        <li>"Renewal Term" means the renewal subscription term for a Service commencing after the Initial Subscription Term or another Renewal Term as specified in an Order Form.</li> <br/> <br/>
                        <strong>2. RESPONSIBILITY FOR REGISTRATION INFORMATION AND CONTENT OF YOUR COMMUNICATIONS</strong>
                        <br /> You may be required to provide information about yourself in order to register for and/or use certain Services. You agree that any such information shall be accurate. You may also be asked to choose a user name and password. You are entirely responsible for maintaining the security of your user name and password and agree not to disclose such to any third party. You agree that you are solely responsible for the content ("Content") sent by you or displayed or uploaded by you in using the Services. You agree that you will not use the Services in a manner that violates applicable law, including but not limited to anti-spam, export control, privacy, and anti-terrorism laws and regulations and laws requiring the consent of subjects of audio and video recordings. You further agree not to use the Services to communicate any message or material that is harassing, libellous, threatening, obscene, and indecent, would violate the intellectual property rights of any party or is otherwise unlawful, that would give rise to civil liability, or that constitutes or encourages conduct that could constitute a criminal offense, under any applicable law or regulation. You further agree not to provide material support or resources (or to conceal or disguise the nature, location, source, or ownership of material support or resources) to any organization(s) designated by the United States government as a foreign terrorist organization pursuant to section 219 of the Immigration and Nationality Act. You further agree not to upload or transmit any software, Content or code that does or is intended to harm, disable, destroy or adversely affect performance of the Services in any way or which does or is intended to harm or extract information or data from other hardware, software or networks of Cloudline or other users of Services. Recognizing the global nature of the Internet, you also agree to comply with applicable local rules or codes of conduct (including codes imposed by your employer) regarding online behavior and acceptable content and the transmission of technical data exported from the United States or the country in which you reside. Cloudline reserves the right to investigate and take appropriate action against anyone who, in Cloudline's sole discretion, is suspected of violating this provision, including without limitation, reporting you to law enforcement authorities. Use of the Services is void where prohibited. Although Cloudline is not responsible for any Content in violation of this provision, Cloudline may delete any such Content of which Cloudline becomes aware, at any time without notice to you. You retain copyright and any other rights you already hold in Content which You submit, post or display on or through, the Services. <br/> <br/>

                        <strong>3. RESPONSIBILITY FOR CONTENT OF OTHERS</strong> <br/>
                         It is possible that other users of the Services ("Users") may violate one or more of the above prohibitions. Cloudline assumes no responsibility or liability for such violation. If you become aware of any violation of this Agreement in connection with use of the Services by any person, please contact Cloudline at sales@cloudline.video. Cloudline may investigate any complaints and violations that come to it's attention and may take any action that it believes is appropriate, including, but not limited to issuing warnings, removing the content or terminating accounts and/or User profiles. However, because situations and interpretations vary, Cloudline also reserves the right not to take any action. Under no circumstances will Cloudline be liable in any way for any data or other content viewed while using the Services, including, but not limited to, any errors or omissions in any such data or content, or any loss or damage of any kind incurred as a result of the use of, access to, or denial of access to any data or content. If at any time you are not happy with the Services, your sole remedy is to cease using the Services. <br/> <br/>

                        <strong>4. ELIGIBILITY</strong> <br/>
                         You affirm that you are of legal age and are otherwise fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in this Agreement, and to abide by and comply with this Agreement. Although we cannot absolutely control whether minors gain unauthorized access to the Services, access may be terminated without warning if we believe that you are underage or otherwise ineligible.<br/><br/>

                        <strong>5. LIMITATIONS ON USE</strong> <br/>
                         The Services may be used for internal business or consumer purposes only. You will not reproduce, resell, or distribute the Services or any reports or data generated by the Services for any purpose unless you have been specifically permitted to do so under a separate agreement with Cloudline. You will not offer or enable any third parties to use the Services purchased by you, display on any website or otherwise publish the Services or any Content obtained from a Service (other than Content created by you) or otherwise generate income from the Services or use the Services for the development, production or marketing of a service or product substantially similar to the Services. You shall not engage in any activity or use the Services in any manner that could damage, disable, overburden, impair or otherwise interfere with or disrupt the Services, or any servers or networks connected to the Services or Cloudline's security systems.  <br/><br/>

                        <strong>6. PROPRIETARY RIGHTS</strong> <br/>
                         Cloudline retains ownership of all proprietary rights in the Services and in all trade names, trademarks, service marks, logos, and domain names ("Cloudline Marks") associated or displayed with the Services. You may not frame or utilize framing techniques to enclose any Cloudline Marks, or other proprietary information (including images, text, page layout, or form) of Cloudline without express written consent. You may not use any meta tags or any other "hidden text" utilizing Cloudline Marks without Cloudline's express written consent. <br/><br/>

                        <strong>7. COPYRIGHT</strong> <br/>
                        Cloudline acknowledges the use of all third party trademarks & copyrights used in this product/service including but not limited to, Digital Ocean Cloud Host Infrastructure, DEBIAN OS, Video conferencing engine 1995 2015 Spirit Corporation Limited, any other third party applications used and/or integrated from time to time. Intellectual Property Rights belong to respective third party products, services, applications and Cloudline does not claim any rights to the same. You may not post, modify, distribute, or reproduce in any way copyrighted material, trademarks, rights of publicity or other proprietary rights without obtaining the prior written consent of the owner of such proprietary rights. Cloudline may deny access to the Services to any User who is alleged to infringe another party's copyright. <br/> <br/>

                        <strong>8. TERMINATION</strong> <br/>
                         The Cloudline website contains information on how to terminate your Account. If you have purchased a Service for a specific term, such termination will be effective on the last day of the then-current term. Your Order Form may provide that a Renewal Term will begin automatically unless either party provides notice of termination at least thirty (30) days prior to the commencement of the next Renewal Term. If you fail to comply with any provision of this Agreement, Cloudline may terminate this Agreement immediately and retain any fees previously paid by you. Sections 2 through 15, inclusive, shall survive any termination of this Agreement. Upon any termination of this Agreement, you must cease any further use of the Services and destroy any copies of associated software within your possession and control. You will not destroy or attempt to harm any Services or associated software on Cloudline's servers or Cloudline's network. <br/><br/>

                        <strong>9. EXPORT RESTRICTIONS</strong> <br/>
                         You acknowledge that the Services, or portion thereof may be subject to the export control laws of India. You will not export, re-export, divert, transfer or disclose any portion of the Services or any related technical information or materials, directly or indirectly, in violation of any applicable export law or regulation. <br/><br/>

                        <strong>10. INJUNCTIVE RELIEF</strong> <br/>
                         You acknowledge that any use of the Services contrary to this Agreement, or any transfer, sublicensing, copying or disclosure of technical information or materials related to the Services, may cause irreparable injury to Cloudline, its affiliates, suppliers and any other party authorized by Cloudline to resell, distribute, or promote the Services ("Resellers"), and under such circumstances Cloudline, its affiliates, suppliers and Resellers will be entitled to equitable relief, without posting bond or other security, including, but not limited to, preliminary and permanent injunctive relief. <br/> <br/>

                        <strong>11. NO WARRANTIES</strong> <br/> 
                        YOU UNDERSTAND AND AGREE THAT THE SERVICES ARE PROVIDED "AS IS" AND CLOUDLINE, ITS AFFILIATES, SUPPLIERS AND RESELLERS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. CLOUDLINE, ITS AFFILIATES, SUPPLIERS AND RESELLERS MAKE NO WARRANTY OR REPRESENTATION REGARDING THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES, REGARDING THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE SERVICES OR THAT THE SERVICES WILL MEET ANY USER'S REQUIREMENTS, OR BE UNINTERRUPTED, TIMELY, SECURE OR ERROR FREE. USE OF THE SERVICES IS AT YOUR SOLE RISK. ANY MATERIAL AND/OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS AT YOUR OWN DISCRETION AND RISK. YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOU RESULTING FROM THE USE OF THE SERVICES. THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SERVICES REMAINS WITH YOU. CLOUDLINE DOES NOT ASSUME ANY RESPONSIBILITY FOR RETENTION OF ANY USER INFORMATION OR COMMUNICATIONS BETWEEN USERS. CLOUDLINE CANNOT GUARANTEE AND DOES NOT PROMISE ANY SPECIFIC RESULTS FROM USE OF THE SERVICES. USE IS AT YOUR OWN RISK. You agree to indemnify, defend and hold harmless Cloudline, its affiliates, officers, directors, employees, consultants, agents, suppliers and Resellers from any and all third party claims, liability, damages and/or costs (including, but not limited to, attorneys' fees) arising from your use of the Services, your violation of this Agreement or the infringement or violation by you or any other user of your account, of any intellectual property or other right of any person or entity. Without limiting the foregoing, the Services are not designed or licensed for use in hazardous environments requiring fail-safe controls, including without limitation operation of nuclear facilities, aircraft navigation/communication systems, air traffic control, and life support or weapons systems. Without limiting the generality of the foregoing, Cloudline, its affiliates, suppliers and Resellers specifically disclaim any express or implied warranty of fitness for such purposes.<br/><br/>

                        <strong>12. PRIVACY</strong> <br/>
                         Use of the Services is also subject to Cloudline's Privacy Policy, a link to which is located at the footer on Cloudline's website, and which is incorporated into this Agreement by this reference. Additionally, you understand and agree that Cloudline may contact you via e-mail or otherwise with information relevant to your use of the Services, regardless of whether you have opted out of receiving such notices. You also agree to have your name and/or email address listed in the header of certain communications you initiate through the Services. <br/><br/>

                        <strong>13. LIMITATION OF LIABILITY</strong> <br/>
                         TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL CLOUDLINE OR ITS AFFILIATES, SUPPLIERS OR RESELLERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, EXEMPLARY OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS OR DAMAGE) ARISING OUT OF THE USE OF OR INABILITY TO USE THE SERVICES OR THE PROVISION OF OR FAILURE TO PROVIDE TECHNICAL OR OTHER SUPPORT SERVICES, WHETHER ARISING IN TORT (INCLUDING NEGLIGENCE) CONTRACT OR ANY OTHER LEGAL THEORY, EVEN IF CLOUDLINE, ITS AFFILIATES, SUPPLIERS OR RESELLERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN ANY CASE, CLOUDLINE'S, ITS AFFILIATES', SUPPLIERS' AND RESELLERS' MAXIMUM CUMULATIVE LIABILITY AND YOUR EXCLUSIVE REMEDY FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT WILL BE LIMITED TO THE AMOUNT ACTUALLY PAID BY YOU FOR THE SERVICES (IF ANY) IN THE TWELVE (12) MONTHS PRECEDING THE EVENT OR CIRCUMSTANCES GIVING RISE TO SUCH CLAIMS. Because some states and jurisdictions do not allow the exclusion or limitation of liability, the above limitation may not apply to you.<br/><br/>

                        <strong>14. MISCELLANEOUS</strong> <br/>
                        <strong>14.1 Choice of Law and Forum</strong> <br/>
                         This Agreement shall be governed by and construed under the laws of the State of Tamil Nadu India, as applied to agreements entered into and to be performed in India  and the District courts in Madurai. <br/><br/>

                        <strong>14.2 Waiver and Severability</strong> <br/>
                         Failure by either party to exercise any of its rights under, or to enforce any provision of, this Agreement will not be deemed a waiver or forfeiture of such rights or ability to enforce such provision. If any provision of this Agreement is held by a court of competent jurisdiction to be illegal, invalid or unenforceable, that provision will be amended to achieve as nearly as possible the same economic effect of the original provision and the remainder of this Agreement will remain in full force and effect. <br/><br/>

                        <strong>14.3 General Provisions</strong> <br/>
                         This Agreement embodies the entire understanding and agreement between the parties respecting the subject matter of this Agreement and supersedes any and all prior understandings and agreements between the parties respecting such subject matter, except that if You or Your company have executed a separate written agreement or you have signed an order form referencing a separate agreement governing your use of the Services, then such agreement shall control to the extent that any provision of this Agreement conflicts with the terms of such agreement. Cloudline may elect to change or supplement the terms of this Agreement from time to time at its sole discretion. Cloudline will exercise commercially reasonable business efforts to provide notice to you of any material changes to this Agreement. Within five (5) business days of posting changes to this Agreement, they will be binding on you. If you do not agree with the changes, you should discontinue using the Services. If you continue using the Services after such five-business-day period, you will be deemed to have accepted the changes to the terms of this Agreement. In order to participate in certain Services, you may be notified that you are required to download software and/or agree to additional terms and conditions. Unless expressly set forth in such additional terms and conditions, those additional terms are hereby incorporated into this Agreement. This Agreement has been prepared in the English Language and such version shall be controlling in all respects and any non-English version of this Agreement is solely for accommodation purposes. All notices or other correspondence to Cloudline under this Agreement must be provided to the email address set forth in Section 9 above, or other contact information as provided by Cloudline for such purpose. Any and all rights and remedies of Cloudline upon your breach or other default under this Agreement will be deemed cumulative and not exclusive of any other right or remedy conferred by this Agreement or by law or equity on Cloudline, and the exercise of any one remedy will not preclude the exercise of any other. The captions and headings appearing in this Agreement are for reference only and will not be considered in construing this Agreement <br/><br/>
                </div>
            </div>
        </div>
    </section>    
</div>
@endsection